= Experience Bottler - Minecraft Mod for Fabric
:image-uri-demo-thumbnail: https://app.box.com/shared/static/jdbl19h8s530e6rfotuj22k0lx7fez2e.png
:image-uri-recipe-experience-bottler: https://app.box.com/shared/static/2belshm5padmppgegk43vpaw0i46j89l.png
:image-uri-bug-report: https://app.box.com/shared/static/g2v3vbju4jazq7kycoigp60ltki2kw8i.png
:image-uri-discord: https://app.box.com/shared/static/0s09ti60hvyyp5k98xyrnkfp683mrt9r.png
:uri-youtube-demo: https://youtu.be/ZtUIFA9R_CE
:uri-license: link:LICENSE
:uri-issues: https://github.com/eideehi/mc-experiencebottler/issues
:uri-fabric: https://fabricmc.net/
:uri-discord: https://discord.gg/DDQqxkK7s6

Add a block that can be used to bottle any quantity of experience points. The bottled experience points can be drunk like a potion, giving the experience points to user.

== How to install
As with other mods, there is nothing special to do, just place the mod files in the mods folder of the environment where Fabric is installed. Also, don't forget about the Fabric API.

== How to use
Experience values can be bottled in any quantity from 1 to 2147483647 into an empty bottle by using the GUI. Up to 64 bottled experience values can be stacked. However, this requires that the quantity of bottled experience must be the same.

A working demo has been uploaded to link:{uri-youtube-demo}[YouTube].
image:{image-uri-demo-thumbnail}[link={uri-youtube-demo},alt="YouTube thumbnail"]

== About rare case bugs
If a player's level is abnormally high, the experience calculation logic may not work correctly. This does not occur unless the player's level exceeds 21863, so it generally doesn't matter to most players, but keep it in the back of your mind.

== Recipes
Experience Bottler::
  image:{image-uri-recipe-experience-bottler}[Recipe - Experience Bottler]

== Languages
|===
|Language |Translators       |Status
|en_us    |Translation Tools |100%
|ja_jp    |EideeHi           |100%
|fr_fr    |ɪѕнɪ_ѕαʍα         |100%
|===

== Contacts
image::{image-uri-bug-report}[link={uri-issues},alt="Bug report on Issues"]
*Only bug reports are accepted under Issues.*

image::{image-uri-discord}[link={uri-discord},alt="eidee.net - Discord Server"]
*Questions, suggestions and comments are welcome on the Discord Server.*

== Credits
* Dependencies:
** {uri-fabric}[Fabric]
* Translators:
** ɪѕнɪ_ѕαʍα (ishi_sama)
* Contributors:
** Kyle Foley (kFo)

== License
Experience Bottler is developed and released under the MIT license. For the full text of the license, please see the {uri-license}[LICENSE] file.
