name: Bug report
description: File a bug report
title: "[ Title that succinctly describes the bug ]"
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction
        This "Issues" section is used purely as a bug tracker. Please post questions or requests on the [Discord server](https://discord.gg/DDQqxkK7s6). If anything other than bug reports is posted in the Issues section, it will generally be ignored and closed without further notice.

        ## Request regarding bug reports
        Please provide as much information as possible in your bug report. Bug reports with too little information may be given lower priority or closed without addressing them (except for simple bugs).

        ## Forms

  - type: checkboxes
    id: searched-existing-issues
    attributes:
      label: Is there an existing issue with the same content?
      description: Search to check if there is an existing issue regarding the bug that occurred.
      options:
        - label: I searched the existing issues.
          required: true

  - type: dropdown
    id: version
    attributes:
      label: Mod version
      options:
        - 1.21+build.1
        - 1.20.6+build.2
        - 1.20.6+build.1
        - 1.20.1+build.2
        - 1.20.1+build.1
        - 1.20+build.1
        - 1.19.4+build.1
        - 1.19.3+build.1
        - 1.19+build.2
        - 1.19+build.1
        - 1.18.2+build.1
        - 1.18.1+build.1
        - 1.18+build.1
        - 1.17.1-4
        - 1.17.1-3
        - 1.17.1-2
        - 1.17.1-1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > With few exceptions, bug fixes for older versions will not be carried out. While we do not prohibit bug reports for older versions as a means to share information with other users, please note that such reports will be labeled "older version" and closed without any fixes being made.

  - type: dropdown
    id: standalone-bug
    attributes:
      label: Can the bug be reproduced with this mod alone?
      description: Please check if the bug occurs with only this mod and its dependencies installed.
      options:
        - I have not checked if the bug occurs with only this mod. Alternatively, it is difficult to check.
        - The bug occurred with this mod alone.
        - The bug did not occur with this mod alone.
    validations:
      required: true

  - type: textarea
    id: mods-when-bug-occurred
    attributes:
      label: List of mods to reproduce bug
      description: |
        Please list the mods you are using if you deem it necessary.
        > [!NOTE]
        > It is generally not necessary to provide this information, but we may ask for it if the cause cannot be determined from the logs alone.
      placeholder: |
        Awesome Weapon v1.2.3
        Awesome NPC v4.5.6
        ...

  - type: textarea
    id: bug-detail
    attributes:
      label: What happened?
      description: Alternatively, please describe what did not happen.
      placeholder: I expected that AAA would become CCC when I did BBB, but it was DDD instead.
    validations:
      required: true

  - type: textarea
    id: steps-for-reproduce-bug
    attributes:
      label: Steps to reproduce the bug
      description: How can this bug be reproduced? Please describe in detail, step by step.
      placeholder: |
        1. Set the configuration to AAA.
        2. Load the save data.
        3. Execute BBB.
        4. After 30 seconds, DDD occurs.
        ...
    validations:
      required: true

  - type: textarea
    id: file-attachments
    attributes:
      label: Logs, screenshots, videos, etc.
      description: |
        You can optionally attach logs, screenshots, or videos by dragging and dropping them. For types of files that can be attached, please refer to "[Attaching files - GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)."
        > [!IMPORTANT]
        > Attaching files is optional, but please try to submit logs whenever possible. Without logs, investigating the bug becomes very difficult.

  - type: markdown
    attributes:
      value: Thank you for your cooperation on the bug report.
